### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by stannam** [STAT547-UBC-2019-20/group_12_qiyangqd_xiaoyuanf#27]
Hi Group 12,

Your research topic sounded interesting. The topic is very timely and supported by large-scale data. Even though it took me some trial and error to get the EDA you intended, once I looked into the plots they looked wonderful. I hope you get an insightful result from this data!

## Is the repository organized in a useful and sensible way?

The organization of the repository was straightforward. Besides, `readme.md` provided a reasonable guide to where each file is located.

## Is there a Usage section in the README?
Yes. 

## Do the scripts run to completion as described in the README?
The script was somewhat ambiguous at some point. `load_data.R` didn't give any message about where the raw data is saved, so it took me some time to actually locate it before feeding it as a parameter for `data_wrangle.R`.

`data_wrangle.R` gave a false message. It said that _the file is saved **in the data folder.**_ which is not necessarily true. You didn't restrict the target path to be ./data so the cleaned data can be anywhere, literally any place the user specifies.

In `eda.R,` I don't think it needs three parameters. It seems that the path to the raw data must be needed for the heat map but then clean_data (which is fully derivative from raw data) doesn't necessarily have to be provided from the user (personal opinion as a lazy user). Finally, I encountered an error while running this, because the third parameter for this script `image_path` was ambiguous from the usage manual: I didn't realize that this should a path to **a folder** but rather assumed this to be a file path just like other parameters. I would like to recommend a warning message or `test_that` to filter out inputs from a stupid user like me.

## Do the scripts produce the expected output?
Yes. 

According to the plots, this group seems to be dealing with a huge dataset. I am looking forward to the result they will derive from this!

## Are the scripts and functions appropriately documented?
No. 

### `data_wrangle.R`

There was a typo: lelete. Generally, it seems you didn't want to follow the convention for documentation, which is not necessarily bad, but it might decrease readability.

You didn't provide documentation for the `save_data()` function!

### `load_data.R` and `eda.R`

You don't need to load an R package one by one, especially if you want to suppress messages: try using `lapply()`.

It is not an excellent practice in the functional programming to put that much content in `main()` as you've done in `eda.R`. The reason is simple. It reduces readability. You may improve by creating other functions that actually do the job and use `main()` as a bridge. By doing so, you can provide better documentation by each function in terms of which parameters are needed and what this specific function does and so on.

## Does it take a long time for the analysis to run? Are there tasks that could be vectorized to make things faster?
No. It didn't take a long time to run. Therefore, the vectorization was not necessary.

**Comment by qiyangqd** [comment]
Hi @stannam ! Thanks for your valuable suggestions! They are constructive and we haven't realized that it is a little hard to let others understand our scripts until you pointed out. We are trying to make our project better. Thanks again!

**Comment by qiyangqd** [comment]
Hi @stannam ! Thanks again for your suggestions! We have addressed most of them, specified as follows:

1. `load_data.R`: It now tells users where the raw data is saved by giving the message  `The cleaned dataset is saved to data/cleaned_data.csv.`
2.  `data_wrangle.R`: 
- Fixed the typo (thanks for pointing it out!).
- For the place where the cleaned data is saved, we added a recommendation in the description, telling users that `It is recommended to save the cleaned data file in the data folder as well.` 
- We also added documentation for the `save_data` function. Actually, we believe your suggestions about documentation is very important, so we modified documentation in all our scripts, following the convention.
3. `eda.R`: 
- We edited `Usage` to remind users of using a path to a folder instead of a path to an image file, and added a recommendation in the description. Now that part of usage is `--image_folder_path=<path_to_the_images_folder>`.
- About the three parameters we used (to load raw data, to load cleaned data, and to save images), we agree that they have not been used fully. That being said, we believe using a command line to import the cleaned data can make the scripts cleaner, so we decided to keep all of them. Yet, we also believe that probably in the future we will change our mind according to specific needs, so we moved this suggestion to __Future work__.
- Reducing content in `main()` is a great suggestion! We have created more functions and added documentation (parameters, desciption) for them. The `main ()` looks better now! 
4. When loading packages, we used the code you provided `lapply()`, which makes the scripts cleaner. Love it!
